CREATE TABLE IF NOT EXISTS CUSTOM_USER (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    `role` VARCHAR(255) NOT NULL
) ENGINE=InnoDB;
